# Generated by Django 4.2.20 on 2025-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snakeuser',
            options={'ordering': ('username',), 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='easy_avg_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Easy mode average score'),
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='easy_hightscore',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Easy mode hightscore'),
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='hard_avg_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hard mode average score'),
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='hard_hightscore',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hard mode hightscore'),
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='medium_avg_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Medium mode average score'),
        ),
        migrations.AddField(
            model_name='snakeuser',
            name='medium_hightscore',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Medium mode hightscore'),
        ),
    ]
