# Generated by Django 4.2.20 on 2025-03-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_snakeuser_options_snakeuser_easy_avg_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snakeuser',
            options={'ordering': ('username',), 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
